In [ ]:
import torch
torch.__version__

'2.3.1+cu121'

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()


7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# Check number of dimensions
MATRIX.ndim

2

In [ ]:
MATRIX.shape


torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 2, 4],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 4],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[1]

tensor([[1, 2, 4],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.5189, 0.5267, 0.1245, 0.8033],
         [0.1893, 0.1150, 0.9440, 0.9592],
         [0.9206, 0.4409, 0.9882, 0.1601]]),
 torch.float32)

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

**Getting information from tensors**

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2997, 0.1607, 0.9483, 0.8889],
        [0.5967, 0.0918, 0.8598, 0.4542],
        [0.1292, 0.7074, 0.9508, 0.6147]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Note: When you run into issues in PyTorch, it's very often one to do with one of the three attributes above.
 So when the error messages show up, sing yourself a little song called "what, what, where":

"what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where" *italicized text*

**BASIC OPERATIONS**

In [ ]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensoraddition = tensor + 10
tensormultiply= tensor * 10
print(tensoraddition)
print(tensormultiply)

tensor([11, 12, 13])
tensor([10, 20, 30])


In [ ]:
torch.multiply(tensor, 10)


tensor([10, 20, 30])

In [ ]:
tensor


tensor([1, 2, 3])

**Matrix Multiplication**

matrix'in çarpılabilmesi için A(m X n) ve B(p x q) ise ilk matrisin sütun sayısı(n) ve ikinci matrisin satır sayısı(p) eşit olmalıdır.

Çarpımın sonucu, boyutları
(m×q) olan yeni bir matris olacaktır.

Note: "@" in Python is the symbol for matrix multiplication.

```
# (3, 2) @ (3, 2) won't work
(2, 3) @ (3, 2) will work
(3, 2) @ (2, 3) will work
```




In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [ ]:
element_wise_multiplication = tensor * tensor
element_wise_multiplication


tensor([1, 4, 9])

In [ ]:
matrix_multiplication = torch.matmul(tensor, tensor)
matrix_multiplication

tensor(14)

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).


In [ ]:
tensor_B_T = tensor_B.T
print(tensor_B.shape)
print(tensor_B_T.shape)


torch.Size([3, 2])
torch.Size([2, 3])


In [ ]:
torch.matmul(tensor_A, tensor_B_T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)


(tensor(90), tensor(0), tensor(45.), tensor(450))

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


Reshaping, stacking, squeezing and unsqueezing



In [ ]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(7, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.]]),
 torch.Size([7, 1]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(7, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.]]),
 torch.Size([7, 1]))

In [ ]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

# İki tensorü stack ile birleştir
result = torch.stack([tensor_a, tensor_b])

print(result)
print(result.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [ ]:
tensor = torch.tensor([1, 2, 3, 4, 5, 6,7,8,9])

# Tensorü 2x3 boyutunda bir görünüme dönüştürme
viewed_tensor = tensor.view(3, 3)

print(viewed_tensor)
print(viewed_tensor.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])


In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [ ]:
x_reshaped.shape

torch.Size([7, 1])

In [ ]:
x_reshaped = x.reshape(1, 7)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [ ]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [ ]:
 #Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [2]:
## INDEXING

# Indexing with pytorch is similar with Numpy

In [3]:
# Create a tensor

import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [4]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
x[0][0]

tensor([1, 2, 3])

In [6]:
x[0][1]

tensor([4, 5, 6])

In [8]:

x[0][0][1]

tensor(2)

In [9]:
#we using : to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [10]:
x[:,:,1]

tensor([[2, 5, 8]])

In [11]:
x[:,1,1]

tensor([5])

In [12]:
x[0,0,:]

tensor([1, 2, 3])

In [13]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor
# burada bir fark var. pytorch'un dtype'ı normalde float32, ama numpy ile etkileşime geçince float64 olarak benimsiyor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [14]:
#Tensor to Numpy Array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [15]:
# change the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [16]:
import numpy as np

# Rastgele tohum belirleyelim
np.random.seed(42)

# Rastgele sayı üret
random_numbers = np.random.rand(5)
print(random_numbers)

#Bu kod çalıştırıldığında, her seferinde aynı random_numbers dizisi elde edilir çünkü np.random.seed(42) komutu RNG'yi aynı başlangıç değerine ayarlamıştır.

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [17]:
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

# şu an burada 2'si de farklı geldi

tensor([[0.8368, 0.4710, 0.8581, 0.9779],
        [0.2020, 0.3853, 0.1180, 0.9565],
        [0.8607, 0.2577, 0.0790, 0.6272]])
tensor([[0.5112, 0.1854, 0.0720, 0.0125],
        [0.2890, 0.3845, 0.3633, 0.0886],
        [0.6968, 0.1401, 0.7823, 0.3028]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [20]:
RANDOM_SEED = 58
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) #burada tekrar yazmamızın sebebi sadece bir block kod için çalışması.
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.4670, 0.3559, 0.5087, 0.1889],
        [0.9914, 0.4001, 0.3592, 0.0564],
        [0.3710, 0.6542, 0.1463, 0.8690]])
tensor([[0.4670, 0.3559, 0.5087, 0.1889],
        [0.9914, 0.4001, 0.3592, 0.0564],
        [0.3710, 0.6542, 0.1463, 0.8690]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
